### ISSUE TITLE
Unable to install mrsFAST

### ISSUE THREAD

**Issue by shivanshss** [sfu-compbio/mrsfast#7]
I use a 64 bit ubuntu 18.04. I tried to install mrsFAST but I got the following error. 
I could not find anything in the manual to help me through this. Would it be possible for you to suggest what I should do to be able to install mrsFAST?

Error details: 

cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o baseFAST.o baseFAST.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o Sort.o Sort.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o MrsFAST.o MrsFAST.c
MrsFAST.c: In function ‘initializeFAST’:
MrsFAST.c:202:25: warning: ‘M’ directive writing 1 byte into a region of size between 0 and 4 [-Wformat-overflow=]
  sprintf(_msf_cigar, "%dM", SEQ_LENGTH);
                         ^
In file included from /usr/include/stdio.h:862:0,
                 from MrsFAST.c:36:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 3 and 7 bytes into a destination of size 5
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o Common.o Common.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o CommandLineParser.o CommandLineParser.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o RefGenome.o RefGenome.c
RefGenome.c: In function ‘initLoadingRefGenome’:
RefGenome.c:61:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(_rg_fp, "%c", &ch);  // '>'
  ^~~~~~~~~~~~~~~~~~~~~~~~~
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o HashTable.o HashTable.c
HashTable.c: In function ‘loadHashTable’:
HashTable.c:646:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&bytesToRead, sizeof(int), 1, _ih_fp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HashTable.c:647:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(_ih_IOBuffer, sizeof(unsigned char), bytesToRead, _ih_fp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o Reads.o Reads.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o Output.o Output.c
cc -fno-pic -DMRSFAST_VERSION=\""3.4.0"\" -DBUILD_DATE=\""Tue Aug 27 14:01:17 IST 2019"\" -DSSE4=0 -O2   -c -o SNPReader.o SNPReader.c
gcc -w baseFAST.o Sort.o MrsFAST.o Common.o CommandLineParser.o RefGenome.o HashTable.o Reads.o Output.o SNPReader.o  HELP.o -o mrsfast  -lz -lm -pthread -lpthread
/usr/bin/ld: baseFAST.o: relocation R_X86_64_32 against undefined symbol `fileName' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: MrsFAST.o: relocation R_X86_64_32S against undefined symbol `_msf_numbers' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: Common.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CommandLineParser.o: relocation R_X86_64_32 against symbol `_binary_HELP_start' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: RefGenome.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: HashTable.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: Reads.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: Output.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: SNPReader.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'mrsfast' failed
make: *** [mrsfast] Error 1

Thank you.

**Comment by vizkidd** [comment]
Edit the Makefile and basically add -no-pie to the end of $(CC) commands, hope it helps:

mrsfast: clean_executables $(objects)
ifeq ($(shell uname -s),Linux)
	$(CC) -w $(objects) -o $@ ${LDFLAGS} ${LIBS} -no-pie
else
	$(CC) -Wl,-no-pie -no_pie -fno-pic -w $(objects) -o $@ ${LDFLAGS} ${LIBS}
endif

snp_indexer: clean_executables SNPIndexer.o
	$(CC) SNPIndexer.o -o $@ ${LDFLAGS} ${LIBS} -no-pie

**Comment by CansuDincer** [comment]
Hello,

Although this issue seems as closed yet, I obtained exactly the same error and I tried your suggestion. Now I have another error:

cc -w baseFAST.o Sort.o MrsFAST.o Common.o CommandLineParser.o RefGenome.o HashTable.o Reads.o Output.o SNPReader.o  HELP.o -o mrsfast  -lz -lm -pthread -lpthread -no-pie
/usr/bin/ld: MrsFAST.o:(.bss+0xdf0): multiple definition of `outputBuffer'; baseFAST.o:(.bss+0x8): first defined here
/usr/bin/ld: MrsFAST.o:(.bss+0xdf8): multiple definition of `outputMeta'; baseFAST.o:(.bss+0x10): first defined here
/usr/bin/ld: MrsFAST.o:(.bss+0xe00): multiple definition of `output'; baseFAST.o:(.bss+0x18): first defined here
/usr/bin/ld: MrsFAST.o:(.bss+0xe08): multiple definition of `finalizeOutput'; baseFAST.o:(.bss+0x20): first defined here
/usr/bin/ld: HashTable.o:(.bss+0xc0): multiple definition of `outputMeta'; baseFAST.o:(.bss+0x10): first defined here
/usr/bin/ld: HashTable.o:(.bss+0xb8): multiple definition of `outputBuffer'; baseFAST.o:(.bss+0x8): first defined here
/usr/bin/ld: HashTable.o:(.bss+0xc8): multiple definition of `output'; baseFAST.o:(.bss+0x18): first defined here
/usr/bin/ld: HashTable.o:(.bss+0xd0): multiple definition of `finalizeOutput'; baseFAST.o:(.bss+0x20): first defined here
/usr/bin/ld: Output.o:(.bss+0x28): multiple definition of `finalizeOutput'; baseFAST.o:(.bss+0x20): first defined here
/usr/bin/ld: Output.o:(.bss+0x20): multiple definition of `output'; baseFAST.o:(.bss+0x18): first defined here
/usr/bin/ld: Output.o:(.bss+0x18): multiple definition of `outputMeta'; baseFAST.o:(.bss+0x10): first defined here
/usr/bin/ld: Output.o:(.bss+0x10): multiple definition of `outputBuffer'; baseFAST.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:18: mrsfast] Error 1

Hope, you can have a solution.

All the best
